name: CI workflow
run-name: CI for social-net
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: install modules
        run: yarn install
      - name: lint project
        run: yarn run lint
      - name: build project
        run: yarn run build
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v16.x, v18.x, v21.x  ]
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: test project
        run: yarn run test
#     - name: run e2e tests
#       run: yarn run test:e2e