name: GitHub Actions CI
run-name: CI run name
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v21.x ]
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: lint project
        run: yarn run lint
      - name: build project
        run: yarn run build
#      - name: run e2e tests
#        run: yarn run test:e2e
